### ISSUE TITLE
Suggestion for "contributing" info

### ISSUE THREAD

**Issue by christinaworkman** [aurooba/sponsor-wp-contributors#7]
I notice the list of contributors is alpha ordered by first name. People seem to generally be following suit when adding themselves. Should this be part of the instructions for adding to the list?

**Comment by aurooba** [comment]
Good idea! I shall add that.

**Comment by aurooba** [comment]
[affea05](https://github.com/aurooba/sponsor-wp-contributors/commit/affea05d6b652d1ad4aa62a597b25ecdf14c0e77)
